# Etapa 1: Build con Node.js
FROM node:22-alpine AS build

WORKDIR /app

# Copiar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el resto del código y compilar Vite
COPY . .
RUN npm run build

# Etapa 2: Servidor con Nginx
FROM nginx:alpine

# Copiar el build del frontend a la carpeta de nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Puerto del frontend
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
